FROM python

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install curl -y
RUN apt-get install build-essential libssl-dev libffi-dev unixodbc-dev -y
RUN pip install --upgrade pip setuptools wheel
RUN apt-get install build-essential -y

ENV PYTHONBUFFERED 1

COPY . .

RUN pip install -r requirements.txt

RUN chmod -x /run.py

CMD ["python", "-m", "run"]